version: "3.7"

services:
  django:
    extends:
      file: ./backend/docker-compose.yml
      service: api
    command: python manage.py runserver
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    volumes:
      - ./backend/:/srv/app
      - static:/srv/app/static
      - media:/srv/app/media
    depends_on:
      - db
  react:
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    command: npm start
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    volumes:
      - ./frontend/:/srv/app
      - /srv/app/node_modules
    depends_on:
      - django
  db:
    image: postgres:12.0-alpine
    container_name: dev-db
    ports:
      - 5432:5432
    env_file: ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media:
  static:
